apiVersion: v1
kind: Namespace
metadata:
  name: receiver-ksvc
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: receiver-ksvc
  namespace: receiver-ksvc
  labels:
    app: receiver-ksvc
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ko://github.com/maschmid/queue-proxy-use-of-closed-network-connection-error/receiver
          name: user-container