apiVersion: v1
kind: Namespace
metadata:
  name: receiver-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-k8s
  namespace: receiver-k8s
spec:
  selector:
    app: receiver-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-k8s
  namespace: receiver-k8s
  labels:
    app: receiver-k8s
spec:
  selector:
    matchLabels:
      app: receiver-k8s
  template:
    metadata:
      labels:
        app: receiver-k8s
    spec:
      containers:
        - image: ko://github.com/maschmid/queue-proxy-use-of-closed-network-connection-error/receiver
          name: user-container
